specfile_path: python-simpleline.spec
upstream_package_name: simpleline
srpm_build_deps:
  - make
actions:
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls *.tar.gz"'
jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches: fedora-development

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-eln

  - job: copr_build
    trigger: commit
    targets:
      - fedora-rawhide
      - fedora-eln
    branch: master
    owner: "@rhinstaller"
    project: Anaconda
    preserve_project: True

  - job: copr_build
    trigger: commit
    targets:
      - fedora-latest
    branch: master
    owner: "@rhinstaller"
    project: Anaconda-devel
    preserve_project: True
