specfile_path: python-simpleline.spec
upstream_package_name: simpleline
upstream_tag_template: simpleline-{version}
actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'cp dist/*.tar.gz .'
    - 'ls *.tar.gz'
jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-development

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
