specfile_path: python-simpleline.spec
upstream_package_name: simpleline
upstream_tag_template: simpleline-{version}
actions:
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls *.tar.gz"'
jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-development

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-eln

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-rawhide
        - fedora-eln
      branch: master
      owner: "@rhinstaller"
      project: Anaconda
      preserve_project: True
