specfile_path: python-simpleline.spec
upstream_package_name: simpleline

actions:
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls *.tar.gz"'

jobs:
  - job: copr_build
    trigger: pull_request
    branch: "1.8"
    targets:
      - centos-stream-9

  - job: copr_build
    trigger: commit
    branch: "1.8"
    targets:
      - centos-stream-9
