specfile_path: python-simpleline.spec
upstream_package_name: simpleline
actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls *.tar.gz"'
jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
