name: validate
on: [push, pull_request]
jobs:
  rawhide:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run test
        run: |
          make container-ci
