name: validate
on: [push, pull_request]
jobs:
  rawhide:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0

      - name: Run test
        run: |
          podman run --rm -v .:/simpleline:Z --workdir /simpleline registry.fedoraproject.org/fedora:rawhide sh -c " \
              dnf install -y python3-pylint python3-gobject-base make; \
              make ci"
