name: validate
on: [push, pull_request]
jobs:
  rawhide:
    runs-on: [self-hosted, red]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: sleep for interactive investigation
        run: sleep infinity
